server:
  port: 8080

spring:
  application:
    name: laboratory
  datasource:
    url: jdbc:mysql://localhost:3306/laboratory?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: laboratory
    password: laboratory
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:cn/navg/laboratory/mapper/**/*.xml  # 使用通配符匹配所有子目录下的XML文件
  type-aliases-package: cn.navg.laboratory.pojo
  configuration:
    map-underscore-to-camel-case: true


# 日志配置
logging:
  charset:
    console: UTF-8
  level:
    #    root: info
    cn.navg.laboratory: debug
    cn.navg.laboratory.mapper.*: debug
    #    org.springframework.web: info
    #    org.springframework.aop: info
    mybatis: debug
    java.sql: debug
    cn.navg.laboratory.mapper: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"